/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Activitati.*;
import datele_mele.DateCity;

import java.awt.Font;
import java.awt.event.ActionListener;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author andre
 */
public class CasaMemGUI extends javax.swing.JInternalFrame {

    DefaultListModel<String> listModel = new DefaultListModel<>();
   // double bill = 0.0;
    int nrCopii;
    int nrAdulti;
    CasaMemoriala casaBilet;


    public CasaMemGUI(int nrCopii, int nrAdulti) {
        initComponents();

        this.nrCopii = nrCopii;
        this.nrAdulti = nrAdulti;
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        DateCity.addVectori();
        jPanel1.setVisible(false);
        pretGhid.setVisible(false);
        valDonare.setVisible(false);
        pretSceneta.setVisible(false);
        Option.setVisible(false);
        Fcaturarea.setVisible(false);
        jTextArea1.setVisible(false);
        jAfis.setVisible(false);
        jBilet.setVisible(false);
        FacturaText.setText("-----------------Factura la Casa Memoriala-----------------");
        FacturaText.append("\n**Nr de copii: " + nrCopii + " **\n**Nr de adulti: " + nrAdulti + " **");

    }

    CasaMemGUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        Fcaturarea = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        FacturaText = new javax.swing.JTextArea();
        jDownload = new javax.swing.JToggleButton();
        jFinish = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        FiltruButton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        ListTIp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ListProgram = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OraText = new javax.swing.JTextField();
        afisFiltru = new javax.swing.JButton();
        Option = new javax.swing.JPanel();
        jGhid = new javax.swing.JRadioButton();
        jSceneta = new javax.swing.JRadioButton();
        jDonare = new javax.swing.JRadioButton();
        valDonare = new javax.swing.JTextField();
        Factura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pretGhid = new javax.swing.JLabel();
        pretSceneta = new javax.swing.JLabel();
        jBilet = new javax.swing.JToggleButton();
        jAfis = new javax.swing.JLabel();
        jNume = new javax.swing.JLabel();

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel5");

        Fcaturarea.setTitle("Factura mea");
        Fcaturarea.setForeground(java.awt.Color.darkGray);
        Fcaturarea.setMinimumSize(new java.awt.Dimension(400, 490));
        Fcaturarea.setType(java.awt.Window.Type.POPUP);

        FacturaText.setEditable(false);
        FacturaText.setBackground(new java.awt.Color(255, 255, 255));
        FacturaText.setColumns(20);
        FacturaText.setRows(5);
        jScrollPane3.setViewportView(FacturaText);

        jDownload.setText("Download");
        jDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDownloadActionPerformed(evt);
            }
        });

        jFinish.setText("Finalizare");
        jFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFinishMouseClicked(evt);
            }
        });
        jFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FcaturareaLayout = new javax.swing.GroupLayout(Fcaturarea.getContentPane());
        Fcaturarea.getContentPane().setLayout(FcaturareaLayout);
        FcaturareaLayout.setHorizontalGroup(
            FcaturareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FcaturareaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FcaturareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FcaturareaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jFinish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDownload)
                        .addGap(16, 16, 16))
                    .addGroup(FcaturareaLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        FcaturareaLayout.setVerticalGroup(
            FcaturareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FcaturareaLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FcaturareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDownload)
                    .addComponent(jFinish))
                .addContainerGap())
        );

        setBackground(new java.awt.Color(153, 204, 255));
        setPreferredSize(new java.awt.Dimension(722, 473));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBackground(new java.awt.Color(0, 204, 204));
        jList1.setMaximumSize(new java.awt.Dimension(205, 168));
        jList1.setMinimumSize(new java.awt.Dimension(205, 168));
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 303, 207));

        jButton2.setText("Afisare");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 74, -1, -1));

        jButton1.setText("Reset");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 102, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("Afisare");

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 46, 258, 110));

        FiltruButton.setText("Filtru");
        FiltruButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiltruButtonMouseClicked(evt);
            }
        });
        FiltruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltruButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FiltruButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 46, 72, -1));

        jPanel1.setOpaque(false);

        ListTIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTIpActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tip Cladire");

        ListProgram.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListProgramActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Program");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("la ora");

        OraText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OraTextActionPerformed(evt);
            }
        });

        afisFiltru.setText("Filtreaza!");
        afisFiltru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afisFiltruMouseClicked(evt);
            }
        });
        afisFiltru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afisFiltruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ListProgram, 0, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OraText, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ListTIp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(afisFiltru)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ListProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(OraText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afisFiltru)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(ListTIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 268, -1, -1));

        Option.setBackground(new java.awt.Color(0, 153, 153));
        Option.setAutoscrolls(true);
        Option.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Option.setFocusCycleRoot(true);

        jGhid.setForeground(new java.awt.Color(255, 255, 255));
        jGhid.setText("Ghid");
        jGhid.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jGhidStateChanged(evt);
            }
        });
        jGhid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGhidActionPerformed(evt);
            }
        });

        jSceneta.setForeground(new java.awt.Color(255, 255, 255));
        jSceneta.setText("Sceneta");
        jSceneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScenetaActionPerformed(evt);
            }
        });

        jDonare.setForeground(new java.awt.Color(255, 255, 255));
        jDonare.setText("Donare");
        jDonare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDonareActionPerformed(evt);
            }
        });

        Factura.setText("Factura");
        Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturaMouseClicked(evt);
            }
        });
        Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturaActionPerformed(evt);
            }
        });

        pretGhid.setForeground(new java.awt.Color(255, 255, 255));
        pretGhid.setText("Pret Ghid");

        pretSceneta.setForeground(new java.awt.Color(255, 255, 255));
        pretSceneta.setText("Pret Sceneta");

        javax.swing.GroupLayout OptionLayout = new javax.swing.GroupLayout(Option);
        Option.setLayout(OptionLayout);
        OptionLayout.setHorizontalGroup(
            OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OptionLayout.createSequentialGroup()
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OptionLayout.createSequentialGroup()
                                .addComponent(jGhid)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionLayout.createSequentialGroup()
                                .addComponent(pretGhid)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDonare)
                            .addComponent(valDonare, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionLayout.createSequentialGroup()
                                .addComponent(jSceneta)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionLayout.createSequentialGroup()
                                .addComponent(pretSceneta)
                                .addGap(37, 37, 37))))
                    .addGroup(OptionLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        OptionLayout.setVerticalGroup(
            OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionLayout.createSequentialGroup()
                .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OptionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGhid)
                            .addComponent(jDonare))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pretGhid)
                            .addComponent(valDonare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(OptionLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jSceneta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(pretSceneta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(Option, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 196, -1, -1));

        jBilet.setText("Cumpar Bilet");
        jBilet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiletActionPerformed(evt);
            }
        });
        getContentPane().add(jBilet, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 162, -1, -1));

        jAfis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jAfis.setForeground(new java.awt.Color(255, 255, 255));
        jAfis.setText("Afisare");
        getContentPane().add(jAfis, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 15, -1, -1));

        jNume.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNume.setForeground(new java.awt.Color(255, 255, 255));
        jNume.setText("Casa Memoriala");
        jNume.setIconTextGap(2);
        jNume.setMaximumSize(new java.awt.Dimension(107, 50));
        getContentPane().add(jNume, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, -1, -1));
        jNume.getAccessibleContext().setAccessibleName("jNume");

        getAccessibleContext().setAccessibleName("jCasaMemoriala");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListProgramActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ListProgramActionPerformed

    private void OraTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OraTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OraTextActionPerformed

    private void FiltruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltruButtonActionPerformed
        // TODO add your handling code here:
        if (FiltruButton.isSelected()) {
            jPanel1.setVisible(true);

            ListProgram.addItem("sa inceapa de");
            ListProgram.addItem("sa se termine de");

            ListTIp.addItem("Casa");
            ListTIp.addItem("Cetate");
            ListTIp.addItem("Conac");
        } else
            jPanel1.setVisible(false);
    }//GEN-LAST:event_FiltruButtonActionPerformed

    private void FiltruButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiltruButtonMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_FiltruButtonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        System.out.println(nrCopii + " " + nrAdulti);

        jAfis.setVisible(true);
        jBilet.setVisible(true);
        jTextArea1.setText(findCasaMemoriala(jList1.getSelectedValue()).toString());
        jTextArea1.setCaretPosition(0); //mentine cursorul in partea sus
        jTextArea1.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void afisFiltruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afisFiltruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afisFiltruActionPerformed

    private void afisFiltruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afisFiltruMouseClicked
    
        listModel.clear();
         for (CasaMemoriala casa : DateCity.vecCasaMemoriala) {
                int selectedProgramIndex = ListProgram.getSelectedIndex();
             int ora = Integer.parseInt(OraText.getText());
 
    if ((selectedProgramIndex == 0 && casa.program[0] >= ora) || 
        (selectedProgramIndex == 1 && casa.program[1] < ora)) {
          if( ListTIp.getSelectedItem() != casa.tipCladire) {
                    listModel.addElement(casa.nume);
          } 

        }
     }
        jList1.setModel(listModel);

    }//GEN-LAST:event_afisFiltruMouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        // TODO add your handling code here:
        listModel.clear();
        for (int i = 0; i < 10; i++) {
            listModel.addElement(DateCity.vecCasaMemoriala.get(i).nume);
        }
        jList1.setModel(listModel);
    }//GEN-LAST:event_jList1KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        listModel.clear();
        jList1.setModel(listModel);
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jGhidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGhidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGhidActionPerformed

    private void jGhidStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jGhidStateChanged
        // TODO add your handling code here:
        if (jGhid.isSelected()) {
            if (casaBilet.ghid == true) {
                pretGhid.setText("Pret poze: " + casaBilet.showThatPrice("Ghid") + " lei");
            } else {
                pretGhid.setText("Nu avem ghid :(");
            }
            pretGhid.setVisible(true);
        } else {
            pretGhid.setVisible(false);
        }


    }//GEN-LAST:event_jGhidStateChanged

    private void jBiletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiletActionPerformed
        // TODO add your handling code here:
        if (jBilet.isSelected()) {
            Option.setVisible(true);
            casaBilet = new CasaMemoriala(findCasaMemoriala(jList1.getSelectedValue()));
            casaBilet.cumparBilet(nrCopii, nrAdulti);
            System.out.println(casaBilet.getBill());

        } else {
            casaBilet.resetBill();
            Option.setVisible(false);
        }

    }//GEN-LAST:event_jBiletActionPerformed

    private void jScenetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScenetaActionPerformed
        // TODO add your handling code here:
        if (jSceneta.isSelected()) {
            pretSceneta.setText("Pret: " + casaBilet.showThatPrice("Sceneta"));
            pretSceneta.setVisible(true);

        } else
            pretSceneta.setVisible(false);
    }//GEN-LAST:event_jScenetaActionPerformed

    private void jDonareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDonareActionPerformed
        // TODO add your handling code here:
        if (jDonare.isSelected())
            valDonare.setVisible(true);
        else
            valDonare.setVisible(false);
    }//GEN-LAST:event_jDonareActionPerformed

    private void FacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseClicked
        // TODO add your handling code here:
        FacturaText.append("\nBilet................................ " + casaBilet.getValBilet(nrCopii, nrAdulti));
        if (jGhid.isSelected()) {
            casaBilet.vreaGhid();
            FacturaText.append("\nPoze................................ " + casaBilet.showThatPrice("Ghid"));
        }
        if (jSceneta.isSelected()) {
            casaBilet.vreaSceneta();
            FacturaText.append("\nPoze................................ " + casaBilet.showThatPrice("Sceneta"));
        }

        if (jDonare.isSelected()) {
            casaBilet.vreaSaDoneze(Integer.parseInt(valDonare.getText()));
            FacturaText.append("\nDonare................................ " + valDonare.getText());

        }

        //bill=casaBilet.getBill();
//        System.out.println(bill);
        FacturaText.append("\n--------------------------------------------------------");
        FacturaText.append("\n                                    TOTAL: " + casaBilet.getBill());
        FacturaText.setFont(new Font("Times new roman", Font.BOLD, 18));
        Fcaturarea.setVisible(true);
    }//GEN-LAST:event_FacturaMouseClicked

    private void jDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDownloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDownloadActionPerformed

    private void FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacturaActionPerformed

    private void ListTIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTIpActionPerformed

    private void jFinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFinishMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jFinishMouseClicked

    private void jFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinishActionPerformed
        // TODO add your handling code here:
        MenuPrincipal.setBill(casaBilet.getBill());
        casaBilet.reset();
        dispose();
    }//GEN-LAST:event_jFinishActionPerformed

    //functie de a gasi mai repede muzue\\
    private CasaMemoriala findCasaMemoriala(String nume) {
        for (int i = 0; i < 10; i++) {
            if (DateCity.vecCasaMemoriala.get(i).nume == nume) {
                return DateCity.vecCasaMemoriala.get(i);
            }
        }
        return new CasaMemoriala();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Factura;
    private javax.swing.JTextArea FacturaText;
    public javax.swing.JFrame Fcaturarea;
    private javax.swing.JToggleButton FiltruButton;
    private javax.swing.JComboBox<String> ListProgram;
    private javax.swing.JComboBox<String> ListTIp;
    private javax.swing.JPanel Option;
    private javax.swing.JTextField OraText;
    private javax.swing.JButton afisFiltru;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jAfis;
    private javax.swing.JToggleButton jBilet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jDonare;
    private javax.swing.JToggleButton jDownload;
    public javax.swing.JButton jFinish;
    private javax.swing.JRadioButton jGhid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel jNume;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jSceneta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel pretGhid;
    private javax.swing.JLabel pretSceneta;
    private javax.swing.JTextField valDonare;
    // End of variables declaration//GEN-END:variables
}
