/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Activitati.*;
import datele_mele.DateCity;
import java.awt.Font;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author andre
 */
public class MuzeuGUI extends javax.swing.JInternalFrame {

    DefaultListModel<String> listModel = new DefaultListModel<>();
    double bill=0.0;
    int nrCopii;
    int nrAdulti;
    Muzeu muzBilet;

    public MuzeuGUI(int nrCopii, int nrAdulti) {
        initComponents();
        this.nrCopii = nrCopii;
        this.nrAdulti = nrAdulti;
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        DateCity.addVectori();
        jPanel1.setVisible(false);
        pretPoze.setVisible(false);
        meniuSuvenir.setVisible(false);
        pretCarti.setVisible(false);
        pretBreloc.setVisible(false);
        pretMagneti.setVisible(false);
        Option.setVisible(false);
        valDonare.setVisible(false);
        Fcaturarea.setVisible(false);
        
        FacturaText.setText("-----------------Factura la muzeu-----------------");
        FacturaText.append("\n**Nr de copii: "+nrCopii+" **\n**Nr de adulti: "+nrAdulti+" **");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        Fcaturarea = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        FacturaText = new javax.swing.JTextArea();
        jDownload = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        FiltruButton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        ListTIp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ListProgram = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OraText = new javax.swing.JTextField();
        afisFiltru = new javax.swing.JButton();
        Option = new javax.swing.JPanel();
        jPoze = new javax.swing.JRadioButton();
        jSuvenir = new javax.swing.JRadioButton();
        jDonare = new javax.swing.JRadioButton();
        valDonare = new javax.swing.JTextField();
        Factura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pretPoze = new javax.swing.JLabel();
        meniuSuvenir = new javax.swing.JPanel();
        jCarti = new javax.swing.JCheckBox();
        jMagneti = new javax.swing.JCheckBox();
        jBreloc = new javax.swing.JCheckBox();
        pretBreloc = new javax.swing.JLabel();
        pretCarti = new javax.swing.JLabel();
        pretMagneti = new javax.swing.JLabel();
        jBilet = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel5");

        Fcaturarea.setTitle("Factura mea");
        Fcaturarea.setForeground(java.awt.Color.darkGray);
        Fcaturarea.setMinimumSize(new java.awt.Dimension(400, 490));
        Fcaturarea.setType(java.awt.Window.Type.POPUP);

        FacturaText.setEditable(false);
        FacturaText.setBackground(new java.awt.Color(255, 255, 255));
        FacturaText.setColumns(20);
        FacturaText.setRows(5);
        jScrollPane3.setViewportView(FacturaText);

        jDownload.setText("Download");
        jDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FcaturareaLayout = new javax.swing.GroupLayout(Fcaturarea.getContentPane());
        Fcaturarea.getContentPane().setLayout(FcaturareaLayout);
        FcaturareaLayout.setHorizontalGroup(
            FcaturareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FcaturareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FcaturareaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDownload)
                .addGap(16, 16, 16))
        );
        FcaturareaLayout.setVerticalGroup(
            FcaturareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FcaturareaLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDownload)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 204, 153));
        setPreferredSize(new java.awt.Dimension(722, 473));
        setVisible(true);

        jList1.setMaximumSize(new java.awt.Dimension(205, 168));
        jList1.setMinimumSize(new java.awt.Dimension(205, 168));
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("Afisare");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("Afisare");

        FiltruButton.setText("Filtru");
        FiltruButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiltruButtonMouseClicked(evt);
            }
        });
        FiltruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltruButtonActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipul");

        ListProgram.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListProgramActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Program");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("la ora");

        OraText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OraTextActionPerformed(evt);
            }
        });

        afisFiltru.setText("Filtreaza!");
        afisFiltru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afisFiltruMouseClicked(evt);
            }
        });
        afisFiltru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afisFiltruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListProgram, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListTIp, 0, 151, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OraText, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(afisFiltru))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ListProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(OraText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ListTIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(afisFiltru))
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Option.setBackground(new java.awt.Color(153, 153, 153));
        Option.setAutoscrolls(true);

        jPoze.setForeground(new java.awt.Color(255, 255, 255));
        jPoze.setText("Poze");
        jPoze.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPozeStateChanged(evt);
            }
        });
        jPoze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPozeActionPerformed(evt);
            }
        });

        jSuvenir.setForeground(new java.awt.Color(255, 255, 255));
        jSuvenir.setText("Suvenir");
        jSuvenir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSuvenirActionPerformed(evt);
            }
        });

        jDonare.setForeground(new java.awt.Color(255, 255, 255));
        jDonare.setText("Donare");
        jDonare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDonareActionPerformed(evt);
            }
        });

        Factura.setText("Factura");
        Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturaMouseClicked(evt);
            }
        });

        pretPoze.setForeground(new java.awt.Color(255, 255, 255));
        pretPoze.setText("jLabel5");

        meniuSuvenir.setOpaque(false);

        jCarti.setForeground(new java.awt.Color(255, 255, 255));
        jCarti.setText("Carti");
        jCarti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCartiActionPerformed(evt);
            }
        });

        jMagneti.setForeground(new java.awt.Color(255, 255, 255));
        jMagneti.setText("Magneti");
        jMagneti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMagnetiActionPerformed(evt);
            }
        });

        jBreloc.setForeground(new java.awt.Color(255, 255, 255));
        jBreloc.setText("Breloc");
        jBreloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrelocActionPerformed(evt);
            }
        });

        pretBreloc.setText("jLabel6");

        pretCarti.setText("jLabel7");

        pretMagneti.setText("jLabel9");

        javax.swing.GroupLayout meniuSuvenirLayout = new javax.swing.GroupLayout(meniuSuvenir);
        meniuSuvenir.setLayout(meniuSuvenirLayout);
        meniuSuvenirLayout.setHorizontalGroup(
            meniuSuvenirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meniuSuvenirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meniuSuvenirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meniuSuvenirLayout.createSequentialGroup()
                        .addComponent(jMagneti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pretMagneti))
                    .addGroup(meniuSuvenirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, meniuSuvenirLayout.createSequentialGroup()
                            .addComponent(jCarti)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pretCarti))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, meniuSuvenirLayout.createSequentialGroup()
                            .addComponent(jBreloc)
                            .addGap(18, 18, 18)
                            .addComponent(pretBreloc))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        meniuSuvenirLayout.setVerticalGroup(
            meniuSuvenirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meniuSuvenirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meniuSuvenirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBreloc)
                    .addComponent(pretBreloc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(meniuSuvenirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCarti)
                    .addComponent(pretCarti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(meniuSuvenirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMagneti)
                    .addComponent(pretMagneti))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout OptionLayout = new javax.swing.GroupLayout(Option);
        Option.setLayout(OptionLayout);
        OptionLayout.setHorizontalGroup(
            OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionLayout.createSequentialGroup()
                .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OptionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pretPoze)
                            .addComponent(jPoze))
                        .addGap(42, 42, 42)
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSuvenir)
                            .addGroup(OptionLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(meniuSuvenir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OptionLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(valDonare, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDonare)))
                    .addGroup(OptionLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, Short.MAX_VALUE))
        );
        OptionLayout.setVerticalGroup(
            OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionLayout.createSequentialGroup()
                .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OptionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPoze))
                    .addGroup(OptionLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSuvenir)
                            .addComponent(jDonare))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valDonare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(pretPoze)
                            .addComponent(meniuSuvenir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jBilet.setText("Cumpar Bilet");
        jBilet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiletActionPerformed(evt);
            }
        });

        jLabel5.setText("Afisare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(Option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBilet)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FiltruButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FiltruButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBilet)
                .addGap(31, 31, 31)
                .addComponent(Option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListProgramActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ListProgramActionPerformed

    private void OraTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OraTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OraTextActionPerformed

    private void FiltruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltruButtonActionPerformed
        // TODO add your handling code here:
        if (FiltruButton.isSelected()) {
            jPanel1.setVisible(true);

            ListProgram.addItem("sa inceapa de");
            ListProgram.addItem("sa se termine de");

            ListTIp.addItem("Istorie");
            ListTIp.addItem("Arte");
            ListTIp.addItem("Stiinte ale naturii");
        } else
            jPanel1.setVisible(false);
    }//GEN-LAST:event_FiltruButtonActionPerformed

    private void FiltruButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiltruButtonMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_FiltruButtonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        System.out.println(nrCopii + " " + nrAdulti);
        for (int i = 0; i < 10; i++)
            if (jList1.getSelectedValue() == DateCity.vecMuzeu.get(i).nume) {
                jTextArea1.setText(DateCity.vecMuzeu.get(i).toString());
                jTextArea1.setCaretPosition(0); //mentine cursorul in partea sus
            }
    }//GEN-LAST:event_jButton2MouseClicked

    private void afisFiltruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afisFiltruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afisFiltruActionPerformed

    private void afisFiltruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afisFiltruMouseClicked
        // TODO add your handling code here:
        int ora = Integer.parseInt(OraText.getText());
        listModel.clear();
        for (int i = 0; i < DateCity.vecMuzeu.size(); i++) {
            if (ListProgram.getSelectedIndex() == 0 && (DateCity.vecMuzeu.get(i).program[0] >= ora && DateCity.vecMuzeu.get(i).tipul == ListTIp.getSelectedItem())) {
                listModel.addElement(DateCity.vecMuzeu.get(i).nume);
            } else if (ListProgram.getSelectedIndex() == 1 && (DateCity.vecMuzeu.get(i).program[1] < ora && DateCity.vecMuzeu.get(i).tipul == ListTIp.getSelectedItem())) {
                listModel.addElement(DateCity.vecMuzeu.get(i).nume);
            }

        }
        jList1.setModel(listModel);

    }//GEN-LAST:event_afisFiltruMouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        // TODO add your handling code here:
        listModel.clear();
        listModel.addElement(DateCity.vecMuzeu.get(0).nume);
        listModel.addElement(DateCity.vecMuzeu.get(1).nume);
        listModel.addElement(DateCity.vecMuzeu.get(2).nume);
        listModel.addElement(DateCity.vecMuzeu.get(3).nume);
        listModel.addElement(DateCity.vecMuzeu.get(4).nume);
        listModel.addElement(DateCity.vecMuzeu.get(5).nume);
        listModel.addElement(DateCity.vecMuzeu.get(6).nume);
        listModel.addElement(DateCity.vecMuzeu.get(7).nume);
        listModel.addElement(DateCity.vecMuzeu.get(8).nume);
        listModel.addElement(DateCity.vecMuzeu.get(9).nume);
        jList1.setModel(listModel);
    }//GEN-LAST:event_jList1KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        listModel.clear();
        jList1.setModel(listModel);
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jPozeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPozeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPozeActionPerformed

    private void jPozeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPozeStateChanged
        // TODO add your handling code here:
        if (jPoze.isSelected()) {
            pretPoze.setText("Pret poze: " + muzBilet.showThatPrice("Poze") + " lei");
            pretPoze.setVisible(true);
        } else {
            pretPoze.setVisible(false);
        }


    }//GEN-LAST:event_jPozeStateChanged

    private void jBiletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiletActionPerformed
        // TODO add your handling code here:
        if (jBilet.isSelected()) {
            Option.setVisible(true);
            muzBilet = new Muzeu(findMuzeu(jList1.getSelectedValue()));
            muzBilet.cumparBilet(nrCopii, nrAdulti);
            System.out.println(muzBilet.getBill());
            
        } else {
            muzBilet.resetBill();
            Option.setVisible(false);
        }

    }//GEN-LAST:event_jBiletActionPerformed

    private void jSuvenirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSuvenirActionPerformed
        // TODO add your handling code here:
        if (jSuvenir.isSelected()) {
            meniuSuvenir.setVisible(true);

        } else
            meniuSuvenir.setVisible(false);
    }//GEN-LAST:event_jSuvenirActionPerformed

    private void jDonareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDonareActionPerformed
        // TODO add your handling code here:
        if (jDonare.isSelected())
            valDonare.setVisible(true);
        else
            valDonare.setVisible(false);
    }//GEN-LAST:event_jDonareActionPerformed

    private void jBrelocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrelocActionPerformed
        // TODO add your handling code here:
        if (jBreloc.isSelected()) {
            pretBreloc.setText(muzBilet.showThatPrice("Breloc") + "lei");
            pretBreloc.setVisible(true);
        } else {
            pretBreloc.setVisible(false);
        }

    }//GEN-LAST:event_jBrelocActionPerformed

    private void jCartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCartiActionPerformed
        // TODO add your handling code here:
        if (jCarti.isSelected()) {
            pretCarti.setText(muzBilet.showThatPrice("Carti") + "lei");
            pretCarti.setVisible(true);
        } else {
            pretCarti.setVisible(false);
        }
    }//GEN-LAST:event_jCartiActionPerformed

    private void jMagnetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMagnetiActionPerformed
        // TODO add your handling code here:
        if (jMagneti.isSelected()) {
            pretMagneti.setText(muzBilet.showThatPrice("Magneti") + "lei");
            pretMagneti.setVisible(true);
        } else {
            pretMagneti.setVisible(false);
        }


    }//GEN-LAST:event_jMagnetiActionPerformed

    private void FacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMouseClicked
        // TODO add your handling code here:
       FacturaText.append("\nBilet................................ "+ muzBilet.getValBilet(nrCopii,nrAdulti));
        if (jPoze.isSelected()) {
            muzBilet.vreaPoze();
             FacturaText.append("\nPoze................................ "+ muzBilet.showThatPrice("Poze"));
        }
        if (jSuvenir.isSelected()) {
            if (jBreloc.isSelected()) {
                muzBilet.vreaSuvenir("Breloc");
                 FacturaText.append("\nBreloc................................ "+ muzBilet.showThatPrice("Breloc"));
            }
            if (jMagneti.isSelected()) {
                muzBilet.vreaSuvenir("Magneti");
                 FacturaText.append("\nMagneti................................ "+ muzBilet.showThatPrice("Magneti"));
            }
            if (jCarti.isSelected()) {
                muzBilet.vreaSuvenir("Carti");
                 FacturaText.append("\nCarti................................ "+ muzBilet.showThatPrice("Carti"));
            }
        }
        
        if(jDonare.isSelected())
        { muzBilet.vreaSaDoneze(Integer.parseInt(valDonare.getText()));
             FacturaText.append("\nDonare................................ "+ valDonare.getText());
        }
        
        bill=muzBilet.getBill();
        System.out.println(bill);
         FacturaText.append("\n--------------------------------------------------------");
          FacturaText.append("\n                                    TOTAL: "+ muzBilet.getBill());
          FacturaText.setFont(new Font("Times new roman",Font.BOLD,18));
        Fcaturarea.setVisible(true);
    }//GEN-LAST:event_FacturaMouseClicked

    private void jDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDownloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDownloadActionPerformed

    //functie de a gasi mai repede muzue\\
    private Muzeu findMuzeu(String nume) {
        for (int i = 0; i < 10; i++) {
            if (DateCity.vecMuzeu.get(i).nume == nume) {
                return DateCity.vecMuzeu.get(i);
            }
        }
        return new Muzeu();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Factura;
    private javax.swing.JTextArea FacturaText;
    private javax.swing.JFrame Fcaturarea;
    private javax.swing.JToggleButton FiltruButton;
    private javax.swing.JComboBox<String> ListProgram;
    private javax.swing.JComboBox<String> ListTIp;
    private javax.swing.JPanel Option;
    private javax.swing.JTextField OraText;
    private javax.swing.JButton afisFiltru;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton jBilet;
    private javax.swing.JCheckBox jBreloc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCarti;
    private javax.swing.JRadioButton jDonare;
    private javax.swing.JToggleButton jDownload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JCheckBox jMagneti;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jPoze;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton jSuvenir;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel meniuSuvenir;
    private javax.swing.JLabel pretBreloc;
    private javax.swing.JLabel pretCarti;
    private javax.swing.JLabel pretMagneti;
    private javax.swing.JLabel pretPoze;
    private javax.swing.JTextField valDonare;
    // End of variables declaration//GEN-END:variables
}
